### ISSUE TITLE
[DOC] - Add set up instructions

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-rpc#12]
# Incorrect Documentation

## Describe the error

The CONTRIBUTING.md file lacks the instructions for setting up a local instance.

## Expected information

Within the `Setting Up Your Code` section, we should add:
- Installing dependencies (`npm ci`)
- Building files (`npm run build`)
- Running linter (`npm run lint`)
- Validating tests (`npm run test`)

**Comment by divyanshu887** [comment]
hello @nhcarrigan  i would like to work on this. could you please assign me

**Comment by nhcarrigan** [comment]
Go for it. :)
