### ISSUE TITLE
[DOC]: Broken usage link

### ISSUE THREAD

**Issue by Vyvy-vi** [nhcarrigan/discord-rpc#3]
# Incorrect Documentation

## Describe the error

The usage instructions linked here-  https://github.com/nhcarrigan/discord-rpc#creating-your-own
link to USAGE.MD.. but USAGE.md is the file in the repo.
## Expected information

To see how to set up your own RPC, view our [usage instructions](https://github.com/nhcarrigan/discord-rpc/blob/main/USAGE.md).

**Comment by nhcarrigan** [comment]
Nice catch - opening this up for first timers 🙂

**Comment by 96RadhikaJadhav** [comment]
@Vyvy-vi  Can I work on the issue?

**Comment by nhcarrigan** [comment]
@96RadhikaJadhav I will assign you to this issue

**Comment by nhcarrigan** [comment]
@all-contributors please add @Vyvy-vi for bugs
